site_name: Soccer Viz
theme:
  name: material
  features:
    -navigation.tabs
    -navigation.selections
    -toc.integrate
    -navigation.top
    -search.suggest
    -search.highlight
    -content.tabs.link
    -content.code.annotation
    -content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/athalakbar13
    - icon: fontawesome/brands/github-alt
      link: https://github.com/athalak13/SoccerViz-Library
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/muhammad-athal-akbar-204aba21b/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright:
   Author <a href="https://github.com/athalak13/SoccerViz-Library" target="_blank" rel="noopener">-- Muhammad Athal Akbar<a/>


